library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from upload.views import image_upload
from main import views

urlpatterns = [
    path('upload/', image_upload, name="upload"),
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]


if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     path('search/', views.search),
#     re_path(r'^books/book/(?P<book_id>\d+)', views.book_page),
#     re_path(r'^books/', views.books),
#     path('about/', views.about),
#     path('contact/', views.contact),
#     path('login/', views.login.as_view()),
#     path('logout/', views.logout_user),
#     path('user/', views.personal_cab),
#     path('register/', views.register.as_view()),
#     path('books/', views.books),
#     path('add/', views.add),
#     path('admin/', admin.site.urls),
#     path('', views.index),
# ]

library/main/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
app_name = 'main'


urlpatterns = [
    # URLы входа и выхода
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='main/reg_log/login.html',
            form_class=LoginForm
        ),
        name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='main/reg_log/logout.html'
        ),
        name='logout'
    ),

    # URLы смены пароля
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='main/reg_log/changePW.html',
            success_url=reverse_lazy('main:personalCab')
        ),
        name='changePW'
    ),
    # Не используется, так как после смены редирект в ЛК
    # path(
    #     'change-password/done/',
    #     auth_views.PasswordChangeDoneView.as_view(template_name='main/reg_log/changePWDone.html'),
    #     name='changePWDone'
    # ),

    # URLы для сброса пароля
    path(
        'reset-password/',
        auth_views.PasswordResetView.as_view(
            template_name='main/reg_log/resetPW.html',
            email_template_name='main/reg_log/resetEmail.html',
            success_url=reverse_lazy('main:resetPWDone')
        ),
        name='resetPW'
    ),
    path(
        'reset-password/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='main/reg_log/resetPWDone.html'
        ),
        name='resetPWDone'
    ),
    path(
        'reset-password/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='main/reg_log/resetPWConfim.html',
            success_url=reverse_lazy('main:index')
        ),
        name='resetPWConfim'
    ),
    # Не используется, так как после сброса редирект на главную
    # path(
    #     'reset-password/complete/',
    #     auth_views.PasswordResetCompleteView.as_view(template_name='main/reg_log/resetPWComplete.html'),
    #     name='resetPWComplete'
    # ),

    path('register/', views.register, name='register'),

    path('user/', views.personal_cab, name='personalCab'),
    path('books/', views.books, name='books'),
    path('books/book/<int:book_id>', views.book_page, name='book_page'),
    path('books/book/<int:book_id>/share', views.book_share, name='book_share'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('', views.index, name='index'),
]

# urlpatterns = [
#     path('search/', views.search),
#     path('add/', views.add),
# ]

library/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='users/', blank=True, default='users/default/nofoto.png')

    def __str__(self):
        return f'Profile of {self.user.username}'

class Author(models.Model):
    name = models.CharField(max_length=150, null=False)
    surname = models.CharField(max_length=150, null=False)

    def __str__(self):
        return f'{self.name} {self.surname}'

class Genre(models.Model):
    name = models.CharField(max_length=150, null=False)
    slug = models.CharField(max_length=150, null=False)

    def __str__(self):
        return f'{self.name}'

class Book(models.Model):
    name = models.CharField(max_length=1000, null=False)
    author = models.ForeignKey(Author, on_delete=models.PROTECT, null=False)
    publication_year = models.IntegerField(null=False)
    publisher = models.CharField(max_length=100, null=False)
    isbn = models.CharField(max_length=100, null=False)
    foto = models.CharField(max_length=100, default='nofoto')
    is_available = models.BooleanField(null=False)

    def __str__(self):
        return f'{self.author.name}: {self.name}'

    def get_absolute_url(self):
        return reverse('main:book_page', args=[self.pk])

class Book_Genre(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return f'{self.book}: {self.genre}'

class User_Reading(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)

library/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label='Имя пользователя',
        label_suffix='',
        widget=forms.TextInput(attrs={'placeholder': 'Придумайте имя пользователя', 'id': 'username'}),

    )
    email = forms.CharField(
        min_length=5,
        label='Email',
        label_suffix='',
        widget=forms.EmailInput(attrs={'placeholder': 'Укажите вашу электронную почту', 'id': 'email'})
    )

    password1 = forms.CharField(
        min_length=5,
        label='Пароль',
        label_suffix='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Придумайте пароль', 'id': 'password'})
    )

    password2 = forms.CharField(
        min_length=5,
        label='Повтор пароля',
        label_suffix='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль', 'id': 'password_rep'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError(' Email already in use.')
        return data


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label='Имя пользователя',
        label_suffix='',
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя', 'id': 'username'}),

    )

    password = forms.CharField(
        min_length=5,
        label='Пароль',
        label_suffix='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль', 'id': 'password'})
    )


class UserEditForm(forms.ModelForm):

    class Meta():
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError(' Email already in use.')
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['foto']
        widgets = {
            'foto': forms.FileInput(attrs={'class': 'inputfile'}),
        }
        labels = {
            'foto': 'Фото профиля'
        }


class BookShareForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        label='Имя отправителя',
        label_suffix='',
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя отправителя', 'id': 'name'})
    )
    email_to = forms.CharField(
        min_length=5,
        label='Почта получателя',
        label_suffix='',
        widget=forms.EmailInput(attrs={'placeholder': 'Укажите электронную почту получателя', 'id': 'email'})
    )
    comment = forms.CharField(
        label='Комментарий',
        label_suffix='',
        widget=forms.Textarea(attrs={'placeholder': 'Комментарий (по желанию)', 'id': 'email'}),
        required=False
    )

library/main/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
import json

from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.contrib import messages

from library import settings
from .forms import *
from .models import *
import random


def index(request):
    random_books = Book.objects.order_by('?')[:5]

    return render(
        request,
        'main/index.html',
        context={
            'random_books': random_books,
        }
    )

def books(request):
    books = Book.objects.all()
    paginator = Paginator(books, 16)

    page = request.GET.get("page")

    book_list = []
    page_obj = paginator.get_page(page)
    for book in page_obj:
        book_list.append(
            {
                'id': book.pk,
                'title': book.name,
                'author': book.author.__str__(),
                'cover': book.foto
            }
        )

    data = {
        'book_list': book_list,
        'page_obj': page_obj
    }

    return render(
        request,
        'main/catalog.html',
        context=data
    )

    # if page == 0:
    #     book_list = []
    #     for book in Book.objects.all():
    #         book_list.append(
    #             {
    #                 'title': book.name,
    #                 'author': book.author.__str__(),
    #                 'cover': book.foto
    #             }
    #         )
    #
    #     data = {
    #         'book_list': paginator.get_page(page_number)
    #     }
    #
    #     return render(
    #         request,
    #         'main/catalog.html',
    #         context=data
    #     )
    # else:
    #     return render(request, 'main/catalog.html')

def add(request):
    output = f'<h2>Форма добавления новой книги</h2>'

    return HttpResponse(output)

def book_page(request, book_id):
    if request.user.is_authenticated:
        user_read_obj = User_Reading.objects.filter(user=request.user.pk)
        user_read_books = [rb.book.pk for rb in user_read_obj]
        if int(book_id) in user_read_books:
            inReadList = True
        else:
            inReadList = False
    else:
        inReadList = False


    if request.method == 'POST':
        if 'addToReadList' in request.POST:
            if not inReadList:
                user_read_obj = User_Reading(user=request.user, book=Book.objects.get(pk=book_id))
                user_read_obj.save()
                inReadList = True
        if 'deleteFromReadList' in request.POST:
            if inReadList:
                user_read_obj = User_Reading.objects.get(user=request.user, book=Book.objects.get(pk=book_id))
                user_read_obj.delete()
                inReadList = False
        if 'share' in request.POST:
            return redirect('main:book_share', book_id=book_id)
            pass



    book = Book.objects.get(pk=book_id)

    book_genries = Book_Genre.objects.filter(book=book_id)
    genries = ''

    for genr in book_genries:
        genries += f'{genr.genre.name}, '



    book_info = {
        'name': book.name,
        'author': book.author.__str__(),
        'publication_year': book.publication_year,
        'publisher': book.publisher,
        'isbn': book.isbn,
        'foto': book.foto,
        'genries': genries.strip(', ')
    }

    data = {
        'book': book_info,
        'inReadList': inReadList
    }

    return render(
        request,
        'main/bookPage.html',
        context=data
    )


def book_share(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    sent = False

    if request.method == 'POST':
        share_form = BookShareForm(request.POST)

        if share_form.is_valid():
            cd = share_form.cleaned_data
            book_url = request.build_absolute_uri(book.get_absolute_url())
            subject = f"{cd['name']} рекомендует прочитать книгу {book}"
            message = (f"Прочитай книгу {book.author}: {book}.\n\n"
                       f"Вот ссылка: {book_url}.\n\n"
                       f"PS: {cd['comment']}")

            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['email_to']])
            sent = True
    else:
        if request.user.is_authenticated:
            share_form = BookShareForm(initial={'name': request.user.username})
        else:
            share_form = BookShareForm()

    return render(request, 'main/bookShare.html', {'book': book, 'share_form': share_form, 'sent': sent})


def search(request):
    s_input = request.GET.get('search', 'None')

    data = {'search_request': s_input}

    return render(request, 'main/search.html', context=data)

def about(request):
    return render(request, 'main/about.html')

def contact(request):
    return render(request, 'main/contact.html')


def register(request):
    if request.method == 'POST':
        reg_form = RegistrationForm(request.POST)
        if reg_form.is_valid():
            new_user = reg_form.save(commit=False)
            new_user.set_password(reg_form.cleaned_data['password1'])
            new_user.save()
            # Создать профиль пользователя, если нужно
            Profile.objects.create(user=new_user)
            return redirect('main:login')
    else:
        reg_form = RegistrationForm()
    data = {'form': reg_form}
    return render(request, 'main/reg_log/register.html', context=data)

@login_required
def personal_cab(request):
    if request.method == 'POST':
        user_form = UserEditForm(
            instance=request.user,
            data=request.POST
        )
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Профиль успешно обновлён')
        else:
            messages.error(request, 'Ошибка обновления профиля')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(
        request,
        'main/personalCab.html',
        context=create_user_data(request, user_form, profile_form)
        )


def create_user_data(request, user_form, profile_form):
    # form = UserInfo(initial={
    #     'username': request.user.username,
    #     'email': request.user.email
    # })

    reading_list = []
    user_reading_list = User_Reading.objects.filter(user=request.user.pk)
    for book in user_reading_list:
        reading_list.append(
            {
                'id': book.book.pk,
                'name': book.book.name,
                'author': book.book.author,
                'foto': book.book.foto
            }
        )

    return {
        'user_form': user_form,
        'profile_form': profile_form,
        'reading_list': reading_list
    }

library/templates/main/reg_log/changePW.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}

<form method="post" class="login_container">
    {% csrf_token %}
    
    {{ form.old_password.label_tag }}
    {{ form.old_password.as_widget }}
    <span class="errors">{{ form.old_password.errors.as_text|linebreaksbr|cut:"* " }}</span>

    {{ form.new_password1.label_tag }}
    {{ form.new_password1.as_widget }}
    <span class="errors">{{ form.new_password1.errors.as_text|linebreaksbr|cut:"* " }}</span>

    {{ form.new_password2.label_tag }}
    {{ form.new_password2.as_widget }}
    <span class="errors">{{ form.new_password2.errors.as_text|linebreaksbr|cut:"* " }}</span>

    <button type="submit">Изменить</button>
</form>

{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/reg_log/changePWDone.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

library/templates/main/reg_log/login.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
<form method="post" class="login_container" action="{% url 'main:login' %}">
    {% csrf_token %}
    <span class="errors">{{ form.non_field_errors.as_text|linebreaksbr|cut:"* " }}</span>
    {{ form.username.label_tag }}
    {{ form.username.as_widget }}
    <!-- <span class="errors">{{ form.username.errors.as_text|linebreaksbr|cut:"* " }}</span> -->
    {{ form.password.label_tag }}
    {{ form.password.as_widget }}
    <!-- <span class="errors">{{ form.password.errors.as_text|linebreaksbr|cut:"* " }}</span> -->
    <input type="hidden" name="next" value="{{ next }}"/>

    <button type="submit" onclick="reg()">Войти</button>
    <span><a href="{% url 'main:register' %}">Ещё нет аккаунта?</a> | <a href="{% url 'main:resetPW' %}">Забыли пароль?</a></span>
</form>

<!-- <div class="login_container">
    <label for="username"><b>Имя пользователя</b></label>
    <input type="text" placeholder="Имя пользователя" id="username" required>

    <label for="password"><b>Пароль</b></label>
    <input type="password" placeholder="Пароль" id="password" required>

    <button type="submit" onclick="log_in()">Войти</button>
</div> -->

<!-- <script>
    function log_in(){
        var us_name = document.getElementById('username').value;
        var pass = document.getElementById('password').value;
        if (us_name.trim() !== '' && pass.trim() !== '') {
            // alert('Вы вошли, возможно');
        } else {
            // alert('Куда!? А данные ввести?');
        }
    }
</script> -->

{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/reg_log/logout.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}

<h1 class="text_plug">Вы успешно вышли из аккаунта</h1>
<p><a href="{% url 'main:login' %}">Войти снова</a></p>

{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/reg_log/register.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
    <!-- <div class="login_container"> -->
        <form method="post" class="login_container">
            {% csrf_token %}
            {{ form.username.label_tag }}
            {{ form.username.as_widget }}
            <span class="errors">{{ form.username.errors.as_text|linebreaksbr|cut:"* " }}</span>
            {{ form.email.label_tag }}
            {{ form.email.as_widget }}
            <span class="errors">{{ form.email.errors.as_text|linebreaksbr|cut:"* " }}</span>
            {{ form.password1.label_tag }}
            {{ form.password1.as_widget }}
            <span class="errors">{{ form.password1.errors.as_text|linebreaksbr|cut:"* " }}</span>
            {{ form.password2.label_tag }}
            {{ form.password2.as_widget }}
            <span class="errors">{{ form.password2.errors.as_text|linebreaksbr|cut:"* " }}</span>

            <button type="submit" onclick="reg()">Создать аккаунт</button>
        </form>

        <!-- <label for="username"><b>Имя пользователя</b></label>
        <input type="text" placeholder="Имя пользователя" id="username" required>

        <label for="email"><b>Email</b></label>
        <input type="email" placeholder="Email" id="email" required>

        <label for="password"><b>Пароль</b></label>
        <input type="password" placeholder="Пароль" id="password" required> -->

        <!-- <button type="submit" onclick="reg()">Создать аккаунт</button> -->
    <!-- </div> -->

    <script>
        function reg(){
            var us_name = document.getElementById('username').value;
            var mail = document.getElementById('email').value;
            var pass = document.getElementById('password').value;
            var pass_rep = document.getElementById('password_rep').value;
            if ((us_name.trim() !== '' && pass.trim() !== '') && (pass_rep == pass)) {
                // alert('Вы зарегались, возможно');
            } else {
                // alert('Куда!? А данные ввести?');
            }
        }
    </script>
{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/reg_log/resetEmail.html
Здравствуйте {{ user.get_username }},

Кто-то запросил новый пароль для вашей учетной записи {{ email }} сервиса Наша Библиотека.

В вашу учетную запись пока не вносились изменения.

Вы можете сбросить свой пароль, перейдя по ссылке ниже:

{{ protocol }}://{{ domain }}{% url 'main:resetPWConfim' uidb64=uid token=token %}

Если вы не запрашивали новый пароль, проигнорируйте это электронное письмо.

Ваша,
Команда Нашей Библиотеки

library/templates/main/reg_log/resetPW.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}

<form method="post" class="login_container">
    {% csrf_token %}
    
    {{ form.email.label_tag }}
    {{ form.email.as_widget }}
    <span class="errors">{{ form.email.errors.as_text|linebreaksbr|cut:"* " }}</span>

    <button type="submit">Сбросить</button>
</form>

{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/reg_log/resetPWConfim.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}

{% if validlink %}
    <form method="post" class="login_container">
        {% csrf_token %}

        {{ form.new_password1.label_tag }}
        {{ form.new_password1.as_widget }}
        <span class="errors">{{ form.new_password1.errors.as_text|linebreaksbr|cut:"* " }}</span>

        {{ form.new_password2.label_tag }}
        {{ form.new_password2.as_widget }}
        <span class="errors">{{ form.new_password2.errors.as_text|linebreaksbr|cut:"* " }}</span>

        <button type="submit">Сохранить новый пароль</button>
    </form>
{% else %}
    <h1 class="text_plug">Недействительная ссылка сброса пароля.</h1>
{% endif %}



{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/reg_log/resetPWDone.html
{% extends "main/base.html" %}
{% load static %}
{% block section %}
    <h1 class="text_plug">Письмо для сброса пароля отправлено на почту. Если вы не получили письмо, проверьте правильность введённой почты.</h1>
{% endblock section %}