library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from upload.views import image_upload
from main import views

urlpatterns = [
    path('upload/', image_upload, name="upload"),
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]


if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     path('search/', views.search),
#     re_path(r'^books/book/(?P<book_id>\d+)', views.book_page),
#     re_path(r'^books/', views.books),
#     path('about/', views.about),
#     path('contact/', views.contact),
#     path('login/', views.login.as_view()),
#     path('logout/', views.logout_user),
#     path('user/', views.personal_cab),
#     path('register/', views.register.as_view()),
#     path('books/', views.books),
#     path('add/', views.add),
#     path('admin/', admin.site.urls),
#     path('', views.index),
# ]

library/main/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
app_name = 'main'


urlpatterns = [
    # URLы входа и выхода
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='main/reg_log/login.html',
            form_class=LoginForm
        ),
        name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='main/reg_log/logout.html'
        ),
        name='logout'
    ),

    # URLы смены пароля
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='main/reg_log/changePW.html',
            success_url=reverse_lazy('main:personalCab')
        ),
        name='changePW'
    ),
    # Не используется, так как после смены редирект в ЛК
    # path(
    #     'change-password/done/',
    #     auth_views.PasswordChangeDoneView.as_view(template_name='main/reg_log/changePWDone.html'),
    #     name='changePWDone'
    # ),

    # URLы для сброса пароля
    path(
        'reset-password/',
        auth_views.PasswordResetView.as_view(
            template_name='main/reg_log/resetPW.html',
            email_template_name='main/reg_log/resetEmail.html',
            success_url=reverse_lazy('main:resetPWDone')
        ),
        name='resetPW'
    ),
    path(
        'reset-password/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='main/reg_log/resetPWDone.html'
        ),
        name='resetPWDone'
    ),
    path(
        'reset-password/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='main/reg_log/resetPWConfim.html',
            success_url=reverse_lazy('main:index')
        ),
        name='resetPWConfim'
    ),
    # Не используется, так как после сброса редирект на главную
    # path(
    #     'reset-password/complete/',
    #     auth_views.PasswordResetCompleteView.as_view(template_name='main/reg_log/resetPWComplete.html'),
    #     name='resetPWComplete'
    # ),

    path('register/', views.register, name='register'),

    path('user/', views.personal_cab, name='personalCab'),
    path('books/', views.books, name='books'),
    path('books/book/<int:book_id>', views.book_page, name='book_page'),
    path('books/book/<int:book_id>/share', views.book_share, name='book_share'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('', views.index, name='index'),
]

# urlpatterns = [
#     path('search/', views.search),
#     path('add/', views.add),
# ]

library/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='users/', blank=True, default='users/default/nofoto.png')

    def __str__(self):
        return f'Profile of {self.user.username}'

class Author(models.Model):
    name = models.CharField(max_length=150, null=False)
    surname = models.CharField(max_length=150, null=False)

    def __str__(self):
        return f'{self.name} {self.surname}'

class Genre(models.Model):
    name = models.CharField(max_length=150, null=False)
    slug = models.CharField(max_length=150, null=False)

    def __str__(self):
        return f'{self.name}'

class Book(models.Model):
    name = models.CharField(max_length=1000, null=False)
    author = models.ForeignKey(Author, on_delete=models.PROTECT, null=False)
    publication_year = models.IntegerField(null=False)
    publisher = models.CharField(max_length=100, null=False)
    isbn = models.CharField(max_length=100, null=False)
    foto = models.CharField(max_length=100, default='nofoto')
    is_available = models.BooleanField(null=False)

    def __str__(self):
        return f'{self.author.name}: {self.name}'

    def get_absolute_url(self):
        return reverse('main:book_page', args=[self.pk])

class Book_Genre(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return f'{self.book}: {self.genre}'

class User_Reading(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)

library/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label='Имя пользователя',
        label_suffix='',
        widget=forms.TextInput(attrs={'placeholder': 'Придумайте имя пользователя', 'id': 'username'}),

    )
    email = forms.CharField(
        min_length=5,
        label='Email',
        label_suffix='',
        widget=forms.EmailInput(attrs={'placeholder': 'Укажите вашу электронную почту', 'id': 'email'})
    )

    password1 = forms.CharField(
        min_length=5,
        label='Пароль',
        label_suffix='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Придумайте пароль', 'id': 'password'})
    )

    password2 = forms.CharField(
        min_length=5,
        label='Повтор пароля',
        label_suffix='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль', 'id': 'password_rep'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError(' Email already in use.')
        return data


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label='Имя пользователя',
        label_suffix='',
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя', 'id': 'username'}),

    )

    password = forms.CharField(
        min_length=5,
        label='Пароль',
        label_suffix='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль', 'id': 'password'})
    )


class UserEditForm(forms.ModelForm):

    class Meta():
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError(' Email already in use.')
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['foto']
        widgets = {
            'foto': forms.FileInput(attrs={'class': 'inputfile'}),
        }
        labels = {
            'foto': 'Фото профиля'
        }


class BookShareForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        label='Имя отправителя',
        label_suffix='',
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя отправителя', 'id': 'name'})
    )
    email_to = forms.CharField(
        min_length=5,
        label='Почта получателя',
        label_suffix='',
        widget=forms.EmailInput(attrs={'placeholder': 'Укажите электронную почту получателя', 'id': 'email'})
    )
    comment = forms.CharField(
        label='Комментарий',
        label_suffix='',
        widget=forms.Textarea(attrs={'placeholder': 'Комментарий (по желанию)', 'id': 'email'}),
        required=False
    )

library/main/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
import json

from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.contrib import messages

from library import settings
from .forms import *
from .models import *
import random


def index(request):
    random_books = Book.objects.order_by('?')[:5]

    return render(
        request,
        'main/index.html',
        context={
            'random_books': random_books,
        }
    )

def books(request):
    books = Book.objects.all()
    paginator = Paginator(books, 16)

    page = request.GET.get("page")

    book_list = []
    page_obj = paginator.get_page(page)
    for book in page_obj:
        book_list.append(
            {
                'id': book.pk,
                'title': book.name,
                'author': book.author.__str__(),
                'cover': book.foto
            }
        )

    data = {
        'book_list': book_list,
        'page_obj': page_obj
    }

    return render(
        request,
        'main/catalog.html',
        context=data
    )

    # if page == 0:
    #     book_list = []
    #     for book in Book.objects.all():
    #         book_list.append(
    #             {
    #                 'title': book.name,
    #                 'author': book.author.__str__(),
    #                 'cover': book.foto
    #             }
    #         )
    #
    #     data = {
    #         'book_list': paginator.get_page(page_number)
    #     }
    #
    #     return render(
    #         request,
    #         'main/catalog.html',
    #         context=data
    #     )
    # else:
    #     return render(request, 'main/catalog.html')

def add(request):
    output = f'<h2>Форма добавления новой книги</h2>'

    return HttpResponse(output)

def book_page(request, book_id):
    if request.user.is_authenticated:
        user_read_obj = User_Reading.objects.filter(user=request.user.pk)
        user_read_books = [rb.book.pk for rb in user_read_obj]
        if int(book_id) in user_read_books:
            inReadList = True
        else:
            inReadList = False
    else:
        inReadList = False


    if request.method == 'POST':
        if 'addToReadList' in request.POST:
            if not inReadList:
                user_read_obj = User_Reading(user=request.user, book=Book.objects.get(pk=book_id))
                user_read_obj.save()
                inReadList = True
        if 'deleteFromReadList' in request.POST:
            if inReadList:
                user_read_obj = User_Reading.objects.get(user=request.user, book=Book.objects.get(pk=book_id))
                user_read_obj.delete()
                inReadList = False
        if 'share' in request.POST:
            return redirect('main:book_share', book_id=book_id)
            pass



    book = Book.objects.get(pk=book_id)

    book_genries = Book_Genre.objects.filter(book=book_id)
    genries = ''

    for genr in book_genries:
        genries += f'{genr.genre.name}, '



    book_info = {
        'name': book.name,
        'author': book.author.__str__(),
        'publication_year': book.publication_year,
        'publisher': book.publisher,
        'isbn': book.isbn,
        'foto': book.foto,
        'genries': genries.strip(', ')
    }

    data = {
        'book': book_info,
        'inReadList': inReadList
    }

    return render(
        request,
        'main/bookPage.html',
        context=data
    )


def book_share(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    sent = False

    if request.method == 'POST':
        share_form = BookShareForm(request.POST)

        if share_form.is_valid():
            cd = share_form.cleaned_data
            book_url = request.build_absolute_uri(book.get_absolute_url())
            subject = f"{cd['name']} рекомендует прочитать книгу {book}"
            message = (f"Прочитай книгу {book.author}: {book}.\n\n"
                       f"Вот ссылка: {book_url}.\n\n"
                       f"PS: {cd['comment']}")

            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd['email_to']])
            sent = True
    else:
        if request.user.is_authenticated:
            share_form = BookShareForm(initial={'name': request.user.username})
        else:
            share_form = BookShareForm()

    return render(request, 'main/bookShare.html', {'book': book, 'share_form': share_form, 'sent': sent})


def search(request):
    s_input = request.GET.get('search', 'None')

    data = {'search_request': s_input}

    return render(request, 'main/search.html', context=data)

def about(request):
    return render(request, 'main/about.html')

def contact(request):
    return render(request, 'main/contact.html')


def register(request):
    if request.method == 'POST':
        reg_form = RegistrationForm(request.POST)
        if reg_form.is_valid():
            new_user = reg_form.save(commit=False)
            new_user.set_password(reg_form.cleaned_data['password1'])
            new_user.save()
            # Создать профиль пользователя, если нужно
            Profile.objects.create(user=new_user)
            return redirect('main:login')
    else:
        reg_form = RegistrationForm()
    data = {'form': reg_form}
    return render(request, 'main/reg_log/register.html', context=data)

@login_required
def personal_cab(request):
    if request.method == 'POST':
        user_form = UserEditForm(
            instance=request.user,
            data=request.POST
        )
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Профиль успешно обновлён')
        else:
            messages.error(request, 'Ошибка обновления профиля')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(
        request,
        'main/personalCab.html',
        context=create_user_data(request, user_form, profile_form)
        )


def create_user_data(request, user_form, profile_form):
    # form = UserInfo(initial={
    #     'username': request.user.username,
    #     'email': request.user.email
    # })

    reading_list = []
    user_reading_list = User_Reading.objects.filter(user=request.user.pk)
    for book in user_reading_list:
        reading_list.append(
            {
                'id': book.book.pk,
                'name': book.book.name,
                'author': book.book.author,
                'foto': book.book.foto
            }
        )

    return {
        'user_form': user_form,
        'profile_form': profile_form,
        'reading_list': reading_list
    }

library/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
    <h1 class="text_plug">Здесь пока что пусто, но когда-нибудь здесть тоже станет хорошо</h1>
{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>Библиотека</title>
</head>
<body>
    <header>
        <a href="../" class="logo-link">
            <img src="{% static 'img/logo.png' %}" alt="Логотип библиотеки" class="logo">
        </a>
        <h1>Добро пожаловать в нашу библиотеку</h1>
        <div class="login_menu">
            <!-- <button onclick="login()" class="lr_butt">
                Войти
            </button>
            <button onclick="register()" class="lr_butt">
                Регистрация
            </button> -->
            {% if request.user.is_authenticated %}
                <span><a href="{% url 'main:personalCab' %}">{{ user.username }}</a></span>
                <form action="{% url 'main:logout' %}?next={{ request.path }}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="lr_butt">Выйти</button>
                </form>
            {% else %}
                <button onclick="login()" class="lr_butt">
                    Войти
                </button>
                <button onclick="register()" class="lr_butt">
                    Регистрация
                </button>
            {% endif %}
            
            
        </div>
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'main:index' %}">Главная</a></li>
            <li><a href="{% url 'main:books' %}">Каталог</a></li>
            <!-- <li><a href="../books/?page=1">Каталог</a></li> -->
            <li><a href="{% url 'main:about' %}">О нас</a></li>
            <li><a href="{% url 'main:contact' %}">Контакты</a></li>
        </ul>
        <div class="search_inp">
            <input type="search" id="search_input" placeholder="Поиск по названию или автору...">
            <button onclick="search()">
                <img src="{% static 'img/search.ico' %}">
            </button>
        </div>
    </nav>
    <section>{% block section %}{% endblock section %}</section>
    <footer>
        <p>&copy; 2023 Библиотека. Все права защищены.</p>
    </footer>

    <script>
        function search() {
          var searchTerm = document.getElementById('search_input').value;
          if (searchTerm.trim() !== '') {
            // Выполнить действия поиска, например, перейти на страницу поиска
            window.location.href = '../search/?search=' + encodeURIComponent(searchTerm);
          } else {
            
          }
        }

        function login() {
          window.location.href = "{% url 'main:login' %}";
        }

        function register() {
          window.location.href = "{% url 'main:register' %}";
        }

        function logout() {
          window.location.href = "{% url 'main:logout' %}";
        }
    </script>
</body>
</html>

library/templates/main/bookPage.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}

<section class="book-info">
    <div class="book-cover">
        <img src="{{ book.foto }}" alt="Обложка книги">
    </div>
    <div class="book-details">
        <h2>{{ book.name }}</h2>
        <p><strong>Автор:</strong> {{ book.author }}</p>
        <p><strong>Жанр:</strong> {{ book.genries }}</p>
        <p><strong>Год издания:</strong> {{ book.publication_year }}</p>
        <p><strong>Издательство:</strong> {{ book.publisher }}</p>
        <p><strong>ISBN:</strong> {{ book.isbn }}</p>

        <form method="post">
          {% csrf_token %}
          {% if request.user.is_authenticated %}
          {%if inReadList %}
          <button type="submit" name="deleteFromReadList">Удалить из списка "Читаю"</button>
          {% else %}
          <button type="submit" name="addToReadList">Добавить в список "Читаю"</button>
          {% endif %}
          {% endif %}
          <button type="submit" name="share">Поделиться</button>
        </form>
    </div>
</section>

<section class="book-description">
    <h3>Описание книги</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae tortor metus. Nullam euismod sapien vel nunc lobortis, nec consequat nibh pellentesque. Sed ac quam non urna imperdiet tincidunt. Fusce commodo, erat in eleifend finibus, nunc elit tristique leo, at lobortis felis mi nec velit. Nulla facilisi. Donec auctor ullamcorper nisi, id varius turpis bibendum eu. Donec aliquam ex vitae lectus vestibulum, sed rhoncus turpis maximus.</p>
</section>

<section class="book-reviews">
    <h3>Отзывы о книге</h3>
    <ul>
      <li>
        <h4>Имя Фамилия</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae tortor metus. Nullam euismod sapien vel nunc lobortis, nec consequat nibh pellentesque.</p>
      </li>
      <li>
        <h4>Имя Фамилия</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae tortor metus. Nullam euismod sapien vel nunc lobortis, nec consequat nibh pellentesque.</p>
      </li>
    </ul>
    <!-- <form>
      <label for="review">Оставить отзыв:</label>
      <textarea id="review" name="review"></textarea>
      <button type="submit">Отправить</button>
    </form> -->
</section>

{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/bookShare.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
    {% if sent %}
        <h1 class="text_plug">Сообщение успешно отправлено</h1>
    {% else %}
        <h1 class="text_plug">Поделится через email</h1>
        <form method="post" class="login_container">
            {% csrf_token %}

            {{ share_form.name.label_tag }}
            {{ share_form.name.as_widget }}
            <span class="errors">{{ share_form.name.errors.as_text|linebreaksbr|cut:"* " }}</span>

            {{ share_form.email_to.label_tag }}
            {{ share_form.email_to.as_widget }}
            <span class="errors">{{ share_form.email_to.errors.as_text|linebreaksbr|cut:"* " }}</span>

            {{ share_form.comment.label_tag }}
            {{ share_form.comment.as_widget }}
            <span class="errors">{{ share_form.comment.errors.as_text|linebreaksbr|cut:"* " }}</span>

            <button type="submit">Поделится</button>
        </form>
    {% endif %}
{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/catalog.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
<div class="catalog_container">
  <aside class="catalog_filters">
    <h2>Фильтры</h2>
    <div id="genreFilters">
      Not yet
      <!-- <label><input type="checkbox" value="fiction"> Художественная литература</label>
      <label><input type="checkbox" value="nonfiction"> Нехудожественная литература</label>
      <label><input type="checkbox" value="fantasy"> Фэнтези</label>
      <label><input type="checkbox" value="science"> Научная литература</label> -->
      <!-- Добавьте другие жанры по необходимости -->
    </div>
      <!-- Добавьте фильтры по вашему усмотрению -->
  </aside>

  <div class="catalog_list">
    <section class="book-cards" id="bookCards">
      <!-- Карточки книг будут добавлены с использованием JavaScript -->
    </section>

    <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">|  &lt;&lt; В начало  |</a>
              <a href="?page={{ page_obj.previous_page_number }}">|  &lt; Предыдущая страница  |</a>
          {% endif %}
  
          <span class="current">
              |  Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}  |
          </span>
  
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">|  Следующая страница &gt;  |</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">|  В конец &gt;&gt;  |</a>
          {% endif %}
      </span>
    </div>
  </div>
</div>


  {{ book_list|json_script:"book_list" }}

  <script>
    document.addEventListener("DOMContentLoaded", function() {
  // Ваши данные о книгах (замените на свои данные)

  const books = JSON.parse(document.getElementById('book_list').textContent);

  const bookCardsContainer = document.getElementById("bookCards");

  // Генерация карточек книг
  books.forEach(book => {
    const bookCard = document.createElement("div");
    bookCard.classList.add("book-card");
    bookCard.innerHTML = `
      <img src="${book.cover}" alt="${book.title}">
      <h3>${truncateText(book.title, 25)}</h3>
      <p>${book.author}</p>
    `;
    bookCard.addEventListener("click", () => {
      // Действия при клике на карточку (например, переход на страницу книги)
      // alert(`Вы выбрали книгу: ${book.title}`);
      window.location.href = 'book/' + book.id;
    });
    bookCardsContainer.appendChild(bookCard);
  });

  // Обрезка текста с добавлением многоточия
  function truncateText(text, maxLength) {
    return text.length > maxLength ? text.slice(0, maxLength) + "..." : text;
  }
});
  </script>
{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/clearable_file_input.html
{% if widget.is_initial %}
    {{ widget.initial_text }}Хуй Пизда Картон: <a href="{{ widget.value.url }}">{{ widget.value }}</a>
    {% if not widget.required %}
        <input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}"
               {% if widget.attrs.disabled %}
                    disabled
               {% endif %}>
        <label for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>
    {% endif %}<br>
    {{ widget.input_text }}:
{% endif %}
<input type="{{ widget.type }}" name="{{ widget.name }}" {% include "django/forms/widgets/attrs.html" %}>

library/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
    <h1 class="text_plug">Не надо с нами связываться, мы не общительные</h1>
{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
<section id="featured-books">
    <h2>Популярные книги</h2>

    {% for book in random_books %}

        <div class="book">
            <a href="{% url 'main:book_page' book.id %}">
                <img src="{{ book.foto }}" alt="Книга">
                <h3>{{ book.name }}</h3>
                <p>Автор: {{ book.author }}</p>
            </a>
        </div>

    {% endfor %}

</section>
{% endblock section %}
{% block footer %}{% endblock footer %}

library/templates/main/personalCab.html
{% extends "main/base.html" %}
{% load static %}
{% block header %}{% endblock header %}
{% block nav %}{% endblock nav %}
{% block section %}
<!-- Личный кабинет пользователя {{ user.username }} заглушка -->
<div class="pers_cab_cont">
  <div class="read_list">
    <h2>Список "Читаю"</h2>
    {% for book in reading_list %}
      <div class="reading_book">
        <a href="../books/book/{{ book.id }}">
          <div class="reading_book_foto">
            <img src="{{ book.foto }}">
          </div>
          <div class="reading_book_info">
            <h3>{{ book.author }}</h3>
            <span>{{ book.name }}</span>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>

  <div class="pers_data">
    <h2>Персональные данные</h2>
    <form method="post" class="login_container" enctype="multipart/form-data">
      {% csrf_token %}

      
      {{ profile_form.foto.label_tag }}
      <img src="{{ profile_form.instance.foto.url }}" alt="Фото профиля" width="100" height="100">
      {{ profile_form.foto.as_widget }}

      {{ user_form.first_name.label_tag }}
      {{ user_form.first_name.as_widget }}
      <span class="errors">{{ user_form.first_name.errors.as_text|linebreaksbr|cut:"* " }}</span>

      {{ user_form.last_name.label_tag }}
      {{ user_form.last_name.as_widget }}
      <span class="errors">{{ user_form.last_name.errors.as_text|linebreaksbr|cut:"* " }}</span>

      {{ user_form.username.label_tag }}
      {{ user_form.username.as_widget }}
      <span class="errors">{{ user_form.username.errors.as_text|linebreaksbr|cut:"* " }}</span>

      {{ user_form.email.label_tag }}
      {{ user_form.email.as_widget }}
      <span class="errors">{{ user_form.email.errors.as_text|linebreaksbr|cut:"* " }}</span>

      <button type="submit">Сохранить изменения</button>

      <span><a href="{% url 'main:changePW' %}">Изменить пароль</a></span>
    </form>
  </div>
</div>
{% endblock section %}
{% block footer %}{% endblock footer %}